version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfile

    # command: python manage.py runserver 0.0.0.0:8000 && python manage.py process_tasks
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    # environment:
    #   POSTGRES_USER: tester
    #   POSTGRES_PASSWORD: tester_password
    #   POSTGRES_DB: protein_db
    image: postgres:latest
    environment:
      # POSTGRES_PASSWORD: test_password
      # POSTGRES_USER: tester
      # POSTGRES_DB: protein_db
      PGDATA: /var/lib/postgresql/data
    restart: unless-stopped
    # networks:
    #   - default
    ports:
      - 5432:5432
    # restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data