# Generated by Django 3.0.4 on 2020-04-04 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=254)),
                ('source', models.CharField(default=None, max_length=254)),
                ('gene', models.CharField(default=None, max_length=254)),
                ('locus_tag', models.CharField(default=None, max_length=254)),
                ('codon_start', models.CharField(default=None, max_length=254)),
                ('product', models.CharField(default=None, max_length=254)),
                ('protein_id', models.CharField(default=None, max_length=254)),
                ('db_xref', models.CharField(default=None, max_length=254)),
                ('sequence', models.CharField(default=None, max_length=65535)),
                ('description', models.CharField(default=-1, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_sequence', models.CharField(max_length=65535, null=True)),
                ('transcribed_sequence', models.CharField(default=None, max_length=65535, null=True)),
                ('search_timestamp', models.DateTimeField()),
                ('protein_matched_beginning_index', models.IntegerField(default=None)),
                ('matched_protein', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='finder.Protein')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
